version: '3.0'

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/insjang/data/wordngin_volume
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/insjang/data/mariadb_volume

services:
  mariadb:
    image: 42_mariadb
    container_name: 42_mariadb
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    tty: yes

  nginx:
    image: 42_nginx
    container_name: 42_nginx
    networks:
      - inception
    build: 
      context: ./requirements/nginx
      dockerfile: ./Dockerfile
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html
    restart: unless-stopped
    tty: yes

  wordpress:
    image: 42_wordpress
    container_name: 42_wordpress
    networks:
      - inception
    build:
      context: ./requirements/wordpress
      dockerfile: ./Dockerfile
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wp:/var/www/html
    restart: unless-stopped
    tty: yes

networks:
  inception:
    driver: bridge