version: '3.0'

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: $PWD/wordpress_Data
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: $PWD/database

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements
      dockerfile: ./Dockerfile
    environment:
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_DB=${MARIADB_DB}
      - MARIADB_ROOT_USER=${MARIADB_ROOT_USER}
      - MARIADB_ROOT_PWD=${MARIADB_ROOT_PWD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_USER_PWD=${MARIADB_USER_PWD}
      # - WORDPRESS_URL=${WORDPRESS_URL}
      # - WORDPRESS_TITLE=${WORDPRESS_TITLE}
      # - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      # - WORDPRESS_ADMIN_USER_PWD=${WORDPRESS_ADMIN_USER_PWD}
      # - WORDPRESS_ADMIN_EMI=${WORDPRESS_ADMIN_EMI}
      # - WORDPRESS_USER=${WORDPRESS_USER}
      # - WORDPRESS_USER_PWD=${WORDPRESS_USER_PWD}
      # - WORDPRESS_USER_EMI=${WORDPRESS_USER_EMI}
      - MYSQL_ALLOW_EMPTY_PASSWORD=${NO}
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    tty: yes #

  nginx:
    container_name: nginx
    build: 
      context: ./requirements/nginx
      dockerfile: ./Dockerfile
    depends_on:
      - wordpress
      - mariadb
    #port 맵핑 local 443 : docker 443
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html
    restart: unless-stopped
    tty: yes #

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: ./Dockerfile
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_DB=${MARIADB_DB}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_USER_PWD=${MARIADB_USER_PWD}
      - WORDPRESS_TITLE=${WORDPRESS_TITLE}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_USER_PWD=${WORDPRESS_ADMIN_USER_PWD}
      - WORDPRESS_ADMIN_EMI=${WORDPRESS_ADMIN_EMI}
      - WORDPRESS_USER=${WORDPRESS_USER}
      - WORDPRESS_USER_PWD=${WORDPRESS_USER_PWD}
      - WORDPRESS_USER_EMI=${WORDPRESS_USER_EMI}
    env_file:
      - .env
    volumes:
      - wp:/var/www/html
    restart: unless-stopped
    tty: yes #


# 컨테이너를 수동으로 정지하기 전까지 재시작
# restart: unless-stopped
networks:
  inception:
    driver: bridge